'use client'

import { useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronDown, CircleAlert, Home, Landmark, Plus, ReceiptText, Search, UserRound, WalletCards, X } from 'lucide-react'

const categories = { active: ['Groceries', 'Transport', 'Internet', 'Rent & utilities'], disabled: ['Travel', 'Gifts'] }
const expenses = [
  { date: 'Today, 09:42', description: 'Fresh Market', amount: -84.2 },
  { date: 'Aug 12, 11:06', description: 'City transit', amount: -42.5 },
  { date: 'Aug 01, 14:40', description: 'Metro card', amount: -28 },
]
const allocations = [
  { date: 'Aug 10', description: 'Monthly plan', amount: 500 },
  { date: 'Aug 05', description: 'Adjusted plan', amount: -100 },
]

type Screen = 'home' | 'ledger' | 'add' | 'budgets' | 'profile'

export default function BudgetsScreen({ onNavigate }: { onNavigate?: (screen: Screen) => void }) {
  const [category, setCategory] = useState('Transport')
  const [start, setStart] = useState('2026-08-01')
  const [end, setEnd] = useState('2026-08-15')
  const [viewed, setViewed] = useState(false)
  const [activeTab, setActiveTab] = useState<'Expenses' | 'Allocations'>('Expenses')
  const [picker, setPicker] = useState(false)
  const [search, setSearch] = useState('')
  const [allocation, setAllocation] = useState('')
  const [allocationType, setAllocationType] = useState<'Allocate' | 'Deallocate'>('Allocate')
  const filtered = useMemo(() => [...categories.active, ...categories.disabled].filter((item) => item.toLowerCase().includes(search.toLowerCase())), [search])
  const disabled = categories.disabled.includes(category)

  return <div className="min-h-screen bg-background pb-24 text-foreground"><main className="mx-auto w-full max-w-lg px-4 pb-6 pt-4">
    {viewed ? <button type="button" onClick={() => setViewed(false)} className="flex w-full items-center justify-between rounded-2xl border border-border bg-card px-4 py-3 text-left shadow-sm"><span className="flex min-w-0 items-center gap-2"><ReceiptText className="size-4 shrink-0 text-primary" /><span className="truncate text-sm font-medium">{category}</span><span className="text-xs text-muted-foreground">{start.slice(5)} – {end.slice(5)}</span></span><ChevronDown className="size-4 shrink-0 text-muted-foreground" /></button> : <section className="rounded-2xl border border-border bg-card p-4 shadow-sm"><div className="flex flex-col gap-3"><button type="button" onClick={() => { setPicker(true); setSearch('') }} className="flex h-12 items-center justify-between rounded-xl border border-border bg-background px-3 text-left"><span className="flex items-center gap-2"><ReceiptText className="size-4 text-muted-foreground" /><span className="text-sm font-medium">{category}</span></span><ChevronDown className="size-4 text-muted-foreground" /></button><div className="grid grid-cols-2 gap-3"><DateField label="From" value={start} onChange={setStart} /><DateField label="To" value={end} onChange={setEnd} /></div><button type="button" onClick={() => setViewed(true)} className="flex h-12 items-center justify-center rounded-xl bg-primary text-sm font-medium text-primary-foreground active:scale-[.99]">View budget</button></div></section>}
    {viewed && <><section className="mt-4 grid grid-cols-2 gap-3"><Metric label="Before range" value="$1,200.00" /><Metric label="Allocated" value="+$500.00" accent /><Metric label="Spent" value="-$154.70" negative /><Metric label="Remaining" value="$1,545.30" accent /></section><section className="mt-4 rounded-2xl border border-border bg-card p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-medium">Plan funds</h2><p className="mt-1 text-xs text-muted-foreground">Add or remove funds for {category}.</p></div><div className="flex rounded-xl bg-secondary p-1">{(['Allocate', 'Deallocate'] as const).map((item) => <button key={item} type="button" onClick={() => setAllocationType(item)} className={`rounded-lg px-2.5 py-1.5 text-[11px] font-medium ${allocationType === item ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground'}`}>{item}</button>)}</div></div><div className="flex gap-2"><div className="relative flex-1"><span className="pointer-events-none absolute left-3 top-3 text-muted-foreground">$</span><input inputMode="decimal" value={allocation} onChange={(event) => setAllocation(event.target.value)} placeholder="0.00" className="h-11 w-full rounded-xl border border-border bg-background pl-7 pr-3 text-sm outline-none focus:border-primary" /></div><button type="button" className="h-11 rounded-xl bg-primary px-4 text-sm font-medium text-primary-foreground">Save</button></div></section><section className="mt-5 rounded-2xl border border-border bg-card p-1 shadow-sm"><div className="grid grid-cols-2 gap-1 rounded-xl bg-secondary p-1">{(['Expenses', 'Allocations'] as const).map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} className={`rounded-lg py-2 text-sm font-medium transition ${activeTab === tab ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground'}`}>{tab}</button>)}</div></section>{activeTab === 'Expenses' ? <Feed title="Expenses" items={expenses} negative /> : <Feed title="Allocations" items={allocations} />}</>}
    {disabled && <div className="mt-4 flex items-center gap-2 rounded-xl bg-secondary px-3 py-2.5 text-xs text-muted-foreground"><CircleAlert className="size-4 shrink-0" />This category is disabled for new entries.</div>}
  </main><nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-card/95 px-2 pb-[env(safe-area-inset-bottom)] pt-2 backdrop-blur"><div className="mx-auto flex max-w-lg items-center justify-around"><NavItem icon={Home} label="Home" onClick={() => onNavigate?.('home')} /><NavItem icon={Landmark} label="Ledger" onClick={() => onNavigate?.('ledger')} /><NavItem icon={Plus} label="Add" onClick={() => onNavigate?.('add')} /><NavItem icon={ReceiptText} label="Budgets" active /><NavItem icon={UserRound} label="Profile" onClick={() => onNavigate?.('profile')} /></div></nav>
    {picker && <div className="fixed inset-0 z-50 flex items-end bg-foreground/30" onClick={() => setPicker(false)}><div role="dialog" aria-modal="true" aria-labelledby="category-picker-title" onClick={(event) => event.stopPropagation()} className="w-full rounded-t-3xl border-t border-border bg-card px-4 pb-8 pt-4 shadow-xl"><div className="mx-auto mb-4 h-1 w-10 rounded-full bg-border" /><div className="mb-4 flex items-center justify-between"><h2 id="category-picker-title" className="text-lg font-semibold">Choose category</h2><button type="button" onClick={() => setPicker(false)} aria-label="Close" className="flex size-9 items-center justify-center rounded-xl text-muted-foreground"><X className="size-4" /></button></div><div className="relative mb-3"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search categories" className="h-11 w-full rounded-xl border border-border bg-background pl-9 pr-3 text-sm outline-none focus:border-primary" /></div><div className="flex max-h-[48vh] flex-col gap-1 overflow-y-auto">{(['Active', 'Disabled'] as const).map((group) => <div key={group} className="flex flex-col gap-1">{group === 'Disabled' && <div className="mt-3 border-t border-border pt-3 text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">Disabled</div>}{group === 'Active' && <div className="mb-1 text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">Active</div>}{filtered.filter((item) => group === 'Active' ? categories.active.includes(item) : categories.disabled.includes(item)).map((item) => <button type="button" key={item} onClick={() => { setCategory(item); setPicker(false) }} className={`flex items-center justify-between rounded-xl px-3 py-3 text-left text-sm ${group === 'Disabled' ? 'text-muted-foreground' : ''}`}><span className="flex items-center gap-2"><ReceiptText className="size-4" />{item}</span>{item === category && <Check className="size-4 text-primary" />}</button>)}</div>)}</div></div></div>}
  </div>
}

function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="flex flex-col gap-1.5"><span className="text-[11px] font-medium uppercase tracking-[0.12em] text-muted-foreground">{label}</span><span className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-3.5 size-4 text-primary" /><input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="h-12 w-full rounded-2xl border border-primary/25 bg-accent/30 pl-9 pr-2 text-sm font-medium outline-none focus:border-primary" /></span></label> }
function Metric({ label, value, accent = false, negative = false }: { label: string; value: string; accent?: boolean; negative?: boolean }) { return <div className="rounded-2xl border border-border bg-card p-3.5 shadow-sm"><p className="text-[11px] font-medium uppercase tracking-[0.1em] text-muted-foreground">{label}</p><p className={`mt-2 text-base font-semibold tabular-nums ${accent ? 'text-primary' : negative ? 'text-destructive' : ''}`}>{value}</p></div> }
function Feed({ title, items, negative = false }: { title: string; items: { date: string; description: string; amount: number }[]; negative?: boolean }) { return <section className="mt-5"><h2 className="mb-3 font-medium">{title}</h2><div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">{items.map((item) => <article key={`${title}-${item.date}-${item.description}`} className="flex items-center justify-between gap-3 border-b border-border px-4 py-3.5 last:border-0"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.description}</p><span className="mt-1 block text-[11px] text-muted-foreground">{item.date}</span></div><span className={`shrink-0 text-sm font-semibold tabular-nums ${negative || item.amount < 0 ? 'text-destructive' : 'text-primary'}`}>{item.amount < 0 ? '-' : '+'}${Math.abs(item.amount).toFixed(2)}</span></article>)}<div className="flex items-center justify-center gap-2 border-t border-border px-4 py-4 text-xs text-muted-foreground"><span className="size-1.5 animate-pulse rounded-full bg-primary" />Loading more {title.toLowerCase()}</div></div></section> }
function NavItem({ icon: Icon, label, active = false, onClick }: { icon: typeof Home; label: string; active?: boolean; onClick?: () => void }) { return <button type="button" onClick={onClick} className={`flex min-w-14 flex-col items-center gap-1 rounded-xl px-2 py-1 text-[10px] ${active ? 'text-primary' : 'text-muted-foreground'}`} aria-current={active ? 'page' : undefined}><span className={`flex size-8 items-center justify-center rounded-xl ${active ? 'bg-primary/10' : ''}`}><Icon aria-hidden="true" className="size-4" /></span>{label}</button> }
