'use client'

import { useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronDown, CircleAlert, Home, Landmark, Plus, ReceiptText, Search, UserRound, WalletCards, X } from 'lucide-react'

const accountGroups = {
  active: ['Cash account', 'Main bank', 'Income account', 'Expense account', 'Savings account'],
  disabled: ['Old savings account', 'Travel card'],
}

const transactions = [
  { date: 'Today, 09:42', description: 'Fresh Market', category: 'Groceries', amount: -84.2 },
  { date: 'Yesterday, 16:18', description: 'Monthly salary', category: '', amount: 3250 },
  { date: 'Aug 12, 11:06', description: 'City transit', category: 'Transport', amount: -42.5 },
  { date: 'Aug 09, 18:24', description: 'Internet bill', category: 'Internet', amount: -65 },
  { date: 'Aug 05, 09:12', description: 'Jordan Williams', category: '', amount: 400 },
  { date: 'Aug 01, 14:40', description: 'Rent payment', category: 'Rent & utilities', amount: -1200 },
]

export function LedgerScreen({ onNavigate }: { onNavigate?: (screen: 'home' | 'ledger' | 'add' | 'budgets' | 'profile') => void }) {
  const [account, setAccount] = useState('Cash account')
  const [start, setStart] = useState('2026-08-01')
  const [end, setEnd] = useState('2026-08-15')
  const [pickerOpen, setPickerOpen] = useState(false)
  const [search, setSearch] = useState('')
  const [hasViewed, setHasViewed] = useState(false)
  const filtered = useMemo(() => [...accountGroups.active, ...accountGroups.disabled].filter((item) => item.toLowerCase().includes(search.toLowerCase())), [search])
  const disabled = accountGroups.disabled.includes(account)

  return <div className="min-h-screen bg-background pb-24 text-foreground"><main className="mx-auto w-full max-w-lg px-4 pb-6 pt-4">
    {hasViewed ? <button type="button" onClick={() => setHasViewed(false)} className="flex w-full items-center justify-between rounded-2xl border border-border bg-card px-4 py-3 text-left shadow-sm"><span className="flex min-w-0 items-center gap-2"><WalletCards className="size-4 shrink-0 text-primary" /><span className="truncate text-sm font-medium">{account}</span><span className="text-xs text-muted-foreground">{start.slice(5)} – {end.slice(5)}</span></span><ChevronDown className="size-4 shrink-0 text-muted-foreground" /></button> : <section className="rounded-2xl border border-border bg-card p-4 shadow-sm"><div className="flex flex-col gap-3"><button type="button" onClick={() => { setPickerOpen(true); setSearch('') }} className="flex h-12 items-center justify-between rounded-xl border border-border bg-background px-3 text-left"><span className="flex items-center gap-2"><WalletCards className="size-4 text-muted-foreground" /><span className="text-sm font-medium">{account}</span></span><ChevronDown className="size-4 text-muted-foreground" /></button><div className="grid grid-cols-2 gap-3"><DateField label="From" value={start} onChange={setStart} /><DateField label="To" value={end} onChange={setEnd} /></div><button type="button" onClick={() => setHasViewed(true)} className="flex h-12 items-center justify-center rounded-xl bg-primary text-sm font-medium text-primary-foreground transition active:scale-[.99]">View ledger</button></div></section>}
    {hasViewed && <><section className="mt-4 grid grid-cols-2 gap-3"><BalanceCard label="Opening balance" value="$1,842.60" /><BalanceCard label="Closing balance" value="$3,800.40" accent /></section><section className="mt-5"><div className="mb-3"><h2 className="font-medium">Transactions</h2></div><div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">{transactions.map((transaction) => <article key={`${transaction.date}-${transaction.description}`} className="flex items-center justify-between gap-3 border-b border-border px-4 py-3.5 last:border-0"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{transaction.description}</p><span className="mt-1 block text-[11px] text-muted-foreground">{transaction.date}</span></div><div className="flex shrink-0 flex-col items-end gap-1"><span className={`text-sm font-semibold tabular-nums ${transaction.amount < 0 ? 'text-destructive' : 'text-primary'}`}>{transaction.amount < 0 ? `-${Math.abs(transaction.amount).toFixed(2)}` : `+${transaction.amount.toFixed(2)}`}</span>{transaction.category && <span className="rounded-full bg-secondary px-2 py-0.5 text-[10px] text-muted-foreground">{transaction.category}</span>}</div></article>)}<div className="flex items-center justify-center gap-2 border-t border-border px-4 py-4 text-xs text-muted-foreground"><span className="size-1.5 animate-pulse rounded-full bg-primary" />Loading more transactions</div></div></section></>}
    {disabled && <div className="mt-4 flex items-center gap-2 rounded-xl bg-secondary px-3 py-2.5 text-xs text-muted-foreground"><CircleAlert className="size-4 shrink-0" />This account is disabled for new entries.</div>}
  </main><nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-card/95 px-2 pb-[env(safe-area-inset-bottom)] pt-2 backdrop-blur"><div className="mx-auto flex max-w-lg items-center justify-around"><NavItem icon={Home} label="Home" onClick={() => onNavigate?.('home')} /><NavItem icon={Landmark} label="Ledger" active /><NavItem icon={Plus} label="Add" onClick={() => onNavigate?.('add')} /><NavItem icon={ReceiptText} label="Budgets" onClick={() => onNavigate?.('budgets')} /><NavItem icon={UserRound} label="Profile" onClick={() => onNavigate?.('profile')} /></div></nav>
    {pickerOpen && <div className="fixed inset-0 z-50 flex items-end bg-foreground/30" onClick={() => setPickerOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="account-picker-title" onClick={(event) => event.stopPropagation()} className="w-full rounded-t-3xl border-t border-border bg-card px-4 pb-8 pt-4 shadow-xl"><div className="mx-auto mb-4 h-1 w-10 rounded-full bg-border" /><div className="mb-4 flex items-center justify-between"><h2 id="account-picker-title" className="text-lg font-semibold">Choose account</h2><button type="button" onClick={() => setPickerOpen(false)} aria-label="Close" className="flex size-9 items-center justify-center rounded-xl text-muted-foreground"><X className="size-4" /></button></div><div className="relative mb-3"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search accounts" className="h-11 w-full rounded-xl border border-border bg-background pl-9 pr-3 text-sm outline-none focus:border-primary" /></div><div className="flex max-h-[48vh] flex-col gap-1 overflow-y-auto">{['Active', 'Disabled'].map((group) => { const items = filtered.filter((item) => group === 'Active' ? accountGroups.active.includes(item) : accountGroups.disabled.includes(item)); return <div key={group} className="flex flex-col gap-1">{group === 'Disabled' && <div className="mt-3 border-t border-border pt-3 text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">Disabled</div>}{group === 'Active' && <div className="mb-1 text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">Active</div>}{items.map((item) => <button type="button" key={item} onClick={() => { setAccount(item); setPickerOpen(false) }} className={`flex items-center justify-between rounded-xl px-3 py-3 text-left text-sm transition hover:bg-secondary ${group === 'Disabled' ? 'text-muted-foreground' : ''}`}><span className="flex items-center gap-2"><span className={`size-2 rounded-full ${group === 'Disabled' ? 'bg-muted-foreground/40' : 'bg-primary'}`} />{item}</span>{item === account && <Check className="size-4 text-primary" />}</button>)}</div> })}</div></div></div>}
  </div>
}

function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="flex flex-col gap-1.5"><span className="text-[11px] font-medium uppercase tracking-[0.12em] text-muted-foreground">{label}</span><span className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-3.5 size-4 text-primary" /><input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="h-12 w-full rounded-2xl border border-primary/25 bg-accent/30 pl-9 pr-2 text-sm font-medium outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20" /></span></label> }
function BalanceCard({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="rounded-2xl border border-border bg-card p-3.5 shadow-sm"><p className="text-[11px] font-medium uppercase tracking-[0.1em] text-muted-foreground">{label}</p><p className={`mt-2 text-base font-semibold tabular-nums ${accent ? 'text-primary' : ''}`}>{value}</p></div> }
function NavItem({ icon: Icon, label, active = false, onClick }: { icon: typeof Home; label: string; active?: boolean; onClick?: () => void }) { return <button type="button" onClick={onClick} className={`flex min-w-14 flex-col items-center gap-1 rounded-xl px-2 py-1 text-[10px] ${active ? 'text-primary' : 'text-muted-foreground'}`} aria-current={active ? 'page' : undefined}><span className={`flex size-8 items-center justify-center rounded-xl ${active ? 'bg-primary/10' : ''}`}><Icon aria-hidden="true" className="size-4" /></span>{label}</button> }

export default LedgerScreen
